# Generated by Django 4.0.5 on 2022-06-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message_wolof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('nom_presonnalite', models.CharField(max_length=100)),
                ('emotion', models.CharField(max_length=50)),
            ],
        ),
    ]
